# ref. https://goreleaser.com/customization/build/
builds:
  - main: ./main
    binary: metalgo
    flags:
      - -v
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: 386
      - goos: windows
        goarch: 386
      - goos: freebsd
        goarch: 386

dockers:
  - image_templates:
      - "metalblockchain/metalgo:{{ .Version }}-amd64"
    dockerfile: .goreleaser/Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
    extra_files:
      - build/plugins/evm
    use: buildx
    goarch: amd64
  - image_templates:
      - "metalblockchain/metalgo:{{ .Version }}-arm64"
    dockerfile: .goreleaser/Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64/v8"
    extra_files:
      - build/plugins/evm
    use: buildx
    goarch: arm64

docker_manifests:
- name_template: "metalblockchain/metalgo:v{{ .Version }}"
  image_templates:
  - metalblockchain/metalgo:{{ .Version }}-amd64
  - metalblockchain/metalgo:{{ .Version }}-arm64

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}-v{{ .Version }}"
    wrap_in_directory: true
    files:
      - src: build/plugins/evm
        dst: plugins
        strip_parent: true

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  github:
    owner: MetalBlockchain
    name: avalanchego
