# ref. https://goreleaser.com/customization/build/
builds:
  - main: ./main
    binary: metalgo
    flags:
      - -v

signs:
  - artifacts: archive

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}-v{{ .Version }}"
    wrap_in_directory: true
    files:
      - src: build/plugins/evm
        dst: plugins
        strip_parent: true

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  github:
    owner: MetalBlockchain
    name: avalanchego
